### PR TITLE
Beware referencing or learning from Eric Elliott

### PR DESCRIPTION
**Pull request by Jeff-Mott-OR**
[Beware](https://www.reddit.com/r/javascript/comments/6q2lk0/why_composition_is_harder_with_classes/dku34cl/)1 [referencing](https://www.reddit.com/r/javascript/comments/5c5lkq/what_eric_elliot_wants_to_say_can_somebody/d9u6tv3/)2 or [learning](https://www.reddit.com/r/javascript/comments/837t82/who_are_some_of_your_favorite_speakers_educators/dvh0br6/)3 from Eric Elliott.

* He is frequently -- almost habitually -- wrong.
* He behaves like a con-man. As another user put it, "What Eric is doing is like a scam artist talking about 'quantum effects' and 'toxin cleansing'. Scammers ride on the popularity of some accepted terms, but reject their meaning and make up some B.S."
* Folks who actually paid for his workshop said it felt like snakeoil.

As for the other two lines I removed, that class inheritance creates taxonomies is *not* a difference with prototypes. Prototypal inheritance creates taxonomies too. `class Dog extends Animal` and `class Cat extends Animal` is equally taxonomical as `const dog = Object.create(animal)` and `const cat = Object.create(animal)`.

And prototypes don't inherently allow for a flat hierarchy. Rather, *multiple inheritance* allows for a flat hierarchy. Multiple inheritance lets you write `class MurderRobotDog extends Barker, Driver, Killer`. Both Python and C++, for example, natively support multiple inheritance. JavaScript's prototype chain supports only single inheritance, but with some manual work, we can mimic multiple inheritance by manually copying properties from one object to another.

### CODE REVIEW

**Comment by fejes713** [comment]
Thanks for contributing! We weren't aware of this so thank you very much for letting us know about this problem. 

I'll just wait for another review and we can merge this right away!

**Comment by skatcat31** [comment]
@fejes713 the removed good to hear section.. Should we replace it with something?

**Comment by fejes713** [comment]
@Chalarangelo will having no `good to hear section` break something in our build and extractor?

**Comment by Chalarangelo** [comment]
@fejes713 I don't think so, Travis builds are passing, so it should be fine.

**Pull request merged**
