### PR TITLE
Update callbacks.md

### PR DESCRIPTION
**Pull request by AdiYElisha**
eventListeners aren't callbacks. they are functions which accept an async callback as it's input.

## Description

**Resolves** #(issue number) 

## What does your PR belong to?

* [x] Questions / Answers
* [ ] Website
* [ ] General / Things regarding the repository (like CI Integration)

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] Enhancement (non-breaking improvement of a question)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

* [x] My code follows the code style of this project.
* [x] My change requires a change to the documentation.
* [x] I have updated the documentation accordingly.
* [x] I have checked that the changes are working properly
* [x] I have checked that there isn't any PR doing the same
* [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by atomiks** [comment]
The event **listener** is the actual function that listens to the event (aka callback), isn't it?

**Comment by AdiYElisha** [comment]
Yeah, exactly

**Comment by atomiks** [comment]
So then there's nothing wrong with the original explanation.

```js
const listener e => console.log(e)
document.addEventListener('click', listener)
```

The listener is the callback. `addEventListener` is a method to make the function/callback listen for the event.

**Comment by AdiYElisha** [comment]
I guess there's nothing wrong with it, but it's unclear what the call back
here, the addEventListenrer or the 'onClick' function.



On Jul 9, 2018 11:46, "atomiks" <notifications@github.com> wrote:

So then there's nothing wrong with the original explanation.

const listener e => console.log(e)document.addEventListener('click', listener)

The listener is the callback. addEventListener is a method to make the
function/callback listen for the event.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fejes713/30-seconds-of-interviews/pull/93#issuecomment-403405883>,
or mute the thread

**Comment by skatcat31** [comment]
The definition of callback makes it fairly clear:

>In computer programming, a callback, also known as a `call-after` function, is any executable code that is passed as an argument to other code, which is expected to call back (execute) the argument at a given time

**Comment by AdiYElisha** [comment]
Right, bit here underlies the problem - without checking another source of
information, it's not ear exactly what is a callback in that example.

On Jul 10, 2018 00:12, "Robert Mennell" <notifications@github.com> wrote:

The definition of callback makes it fairly clear:

In computer programming, a callback, also known as a call-after function,
is any executable code that is passed as an argument to other code, which
is expected to call back (execute) the argument at a given time

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/fejes713/30-seconds-of-interviews/pull/93#issuecomment-403622205>,
or mute the thread

**Comment by skatcat31** [comment]
from the paragraph directly above suggested change:

> Callbacks are functions passed as an argument to another function to be executed once an event has occurred or a certain task is complete, often used in asynchronous code. Callback functions are invoked later by a piece of code but can be declared on initialization without being invoked.

**Comment by skatcat31** [comment]
Since it's been more than a few days since last conversation and the above paragraph illustrates what a callback is I'll be closing this MR. Thanks for submitting! If you find anything else you'd like to contribute don't hesitate.

**Pull request closed without merging**
