### PR TITLE
fix: removed overhead ( str.slice )

### PR DESCRIPTION
**Pull request by gavrashenko**
## Description

**Resolves** #(issue number) 

## What does your PR belong to?

* [x] Questions / Answers
* [ ] Website
* [ ] General / Things regarding the repository (like CI Integration)

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] Enhancement (non-breaking improvement of a question)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

* [x] My code follows the code style of this project.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [x] I have checked that the changes are working properly
* [x] I have checked that there isn't any PR doing the same
* [x] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by atomiks** [comment]
Should be `Math.max(0, str.length - 4)` as passing a negative number to `repeat` throws an error..

**Comment by fejes713** [comment]
Thanks for contributing!

@atomiks what's your opinion? Do we keep our solution or merge this one? Having `Math.max` seems more complex to me compared to our solution. How about performance?

**Comment by skatcat31** [comment]
Before decision: The description would also need an update... otherwise having `Using `String.prototype.slice()`, we can grab a portion of the string from index `0` (first character) to index `-4` (5th last character) and calculate the resulting length,` in the explanation gets a little confusing

**Comment by skatcat31** [comment]
As for performance difference in browsers:

`str.slice(0, -4).length` behaves the same as `str.length - 4` on a 22848 character string as measured by `performance.now()` steps showed a whopping result to the fourth digit of... 0

**Comment by skatcat31** [comment]
Updated description. @fejes713 this should be good to merge

**Comment by atomiks** [comment]
@skatcat31 it's not because if the string length is `0-3` it will throw an error due to a negative number being passed. It needs to use `Math.max`

**Comment by fejes713** [comment]
```js
const mask = (str, maskChar = "#") =>
    maskChar.repeat(Math.max(0, str.length - 4)) + str.slice(-4)
```

```js
const mask = (str, maskChar = "#") =>
  maskChar.repeat(str.slice(0, -4).length) + str.slice(-4)
```

In terms of readability, I am not sure which one to pick. The current solution we have is perfectly fine to me. What is your opinion @atomiks ?

Also I would like to hear feedback from @Chalarangelo since this question is partialy taken from 30code.

**Comment by skatcat31** [comment]
@atomiks fair. I did forget that. In that case those string would be considered un-maskable and should throw an error if we wanted these examples to be production ready.

**Comment by skatcat31** [comment]
I'm curious if we should change the question to make it a little more clear? I'm pretty sure we don't want it this verbose though... considering this would be a library like factory function
____

### Given a String of sufficient length and an amount of characters to remain visible, return a function that will accept a String to mask and a mask character. Default the character to `#`, and throw on a String that is not long enough

```js
const makeMask = (length, visible) => function( str, mask = '#' ){
  if (str.length < length) throw new Error('Provided String is not long enough. The string must be of length ' + length);
  return mask.repeat(str.slice(0, -1 * visible).length) + str.slice(-1 * visible);
}
```

### Good to Hear
...

___

Maybe it's better to think about which implicit case we want?

 - Throw on not long enough
 - Return a masked string of the minimum length plus the last four characters of the source string

Either way this isn't very secure unless it's only done on a server... but that's a different question entirely

**Comment by skatcat31** [comment]
I'm going to be closing this since there hasn't been any activity on it to resolve how we'd actually want to change it. Currently it sounds like the string.slice is used for safety reasons before performance reasons, which means we want to leave it

**Comment by Robe21** [comment]
😁

**Pull request closed without merging**
