### PR TITLE
better answer for mask

### PR DESCRIPTION
**Pull request by volny**
## Description

**Resolves** #(issue number) 

## What does your PR belong to?

* [x] Questions / Answers
* [ ] Website
* [ ] General / Things regarding the repository (like CI Integration)

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] Enhancement (non-breaking improvement of a question)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

* [x] My code follows the code style of this project.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [x] I have checked that the changes are working properly
* [ ] I have checked that there isn't any PR doing the same
* [ ] I have read the **CONTRIBUTING** document.

### CODE REVIEW

**Comment by skatcat31** [comment]
Produces a range error on 3 characters:

```js
Uncaught RangeError: Invalid count value
    at String.repeat (<anonymous>)
    at mask (<anonymous>:2:12)
    at <anonymous>:1:1
```

**Comment by skatcat31** [comment]
Sorry did not meant to close. If you can still find a better answer then we'd still love the PR

**Comment by atomiks** [comment]
Yeah we already went through this 😆 `str.slice()` guards against the error above. Alternative is `Math.max()` but it doesn't really make a perf difference from what we tested...

**Comment by volny** [comment]
Yup, didn't think about short strings

**Pull request closed without merging**
